# Generated by Django 4.0.3 on 2022-04-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('payment_method_ic', models.CharField(max_length=30)),
                ('inicial_contributions', models.DecimalField(decimal_places=2, max_digits=11)),
                ('payment_method_is', models.CharField(max_length=30)),
                ('initial_savings', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
