# Generated by Django 4.0.3 on 2022-04-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_registerform_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerform',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
