# Generated by Django 4.0.3 on 2022-05-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_registerform_email_registerform_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateTimeField()),
                ('cedula', models.CharField(max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=11)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
