# Generated by Django 4.0.3 on 2022-05-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_loanform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanform',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
